runTask4 : task4.o
	gcc -o task4_exe task4.o
	./task4_exe 

runTask3 : task3.o
	gcc -o task3_exe task3.o
	./task3_exe 

task4.o : task4.c 
	gcc -c task4.c

task3.o : task3.c 
	gcc -c task3.c
	

clean : 
	rm *.o
	rm *_exe