clean : 
		rm *_exe
		rm *.o

task5 : task5_exe
		./task5_exe

task5_exe : task5.o
			gcc -o task5_exe task5.o

task5.o : task5.c 
		  gcc -c task5.c 

task6 : task6_exe
		./task6_exe

task6_exe : task6.o
			gcc -o task6_exe task6.o

task6.o : task6.c 
		  gcc -c task6.c 

home_ex3 : home_ex3_exe
		./home_ex3_exe

home_ex3_exe : home_ex3.o
			gcc -o home_ex3_exe home_ex3.o

home_ex3.o : home_ex3.c
		  gcc -c home_ex3.c