clean : 
		rm *_exe
		rm *.o

task7 : task7_exe
		./task7_exe

task7_exe : task7.o
			gcc -o task7_exe task7.o

task7.o : task7.c 
		  gcc -c task7.c 

task8 : task8_exe
		./task8_exe

task8_exe : task8.o
			gcc -o task8_exe task8.o

task8.o : task8.c
		  gcc -c task8.c

home_ex5 : home_ex5_exe
		./home_ex5_exe

home_ex5_exe : home_ex5.o
			gcc -o home_ex5_exe home_ex5.o

home_ex5.o : home_ex5.c
		  gcc -c home_ex5.c

home_ex6 : home_ex6_exe
		./home_ex6_exe

home_ex6_exe : home_ex6.o
			gcc -o home_ex6_exe home_ex6.o

home_ex6.o : home_ex6.c
		  gcc -c home_ex6.c

task9 : task9_exe
		./task9_exe

task9_exe : task9.o
			gcc -o task9_exe task9.o

task9.o : task9.c 
		  gcc -c task9.c 

