clean : 
		rm *_exe
		rm *.o

task7 : task7_exe
		./task7_exe

task7_exe : task7.o
			gcc -o task7_exe task7.o

task7.o : task7.c 
		  gcc -c task7.c 

task8 : task8_exe
		./task8_exe

task8_exe : task8.o
			gcc -o task8_exe task8.o

task8.o : task8.c
		  gcc -c task8.c